name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build-and-test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Build Docker image
              run: docker build -t laladesk/docker-volume -f Dockerfile.dev .

            - name: Run tests
              run: docker run -e CI=true laladesk/docker-volume npm run test
